sudo: required

language: java

jdk:
  - openjdk8

services:
  - docker

branches:
  only:
    - feature/campaign

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
before_install:
  - chmod +x gradlew
  - ./gradlew clean build
#  - docker build -t tjsrua02/docker-practice -f Dockerfile.dev .


script:
  - docker build --build-arg JAR_FILE=build/libs/Joopging-0.0.1-SNAPSHOT.jar -t tjsrua02/docker-practice .

#  - docker login -u tjsrua02 -p dnflwlq123
#  - docker push tjsrua02/docker-practice
#  - sudo apt-get update

deploy:
  provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
  secret_access_key: $AWS_SECRET_KEY
  region: "ap-northeast-2"
  app: "Joopgging-final"
  env: "Joopggingfinal-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-168712278800"  # S3 bucket name
  bucket_path: "Joopgging-final"
  on:
    branch: feature/campaign

after_deploy:
  - echo "Elastic Beanstalk 배포 진행중입니다 ."